config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

from expenshare.index.views import index

urlpatterns = [
    path("", index, name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("expenshare.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    path(
        "policy/",
        TemplateView.as_view(template_name="pages/policy.html"),
        name="policy",
    ),
    path(
        "terms/", TemplateView.as_view(template_name="pages/terms.html"), name="terms"
    ),
    # Your stuff: custom urls includes go here
    path("sharelists/", include("expenshare.sharelists.urls", namespace="sharelists")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

expenshare/sharelists/urls.py
from django.urls import path

from expenshare.sharelists.views import (
    CreditCreate,
    CreditDelete,
    CreditUpdate,
    CreditView,
    SharelistCreate,
    SharelistMain,
    SharelistSummary,
)

app_name = "sharelists"
urlpatterns = [
    path("create", SharelistCreate.as_view(), name="create"),
    path("<int:sharelist_id>", SharelistMain.as_view(), name="view"),
    path("<int:sharelist_id>/summary", SharelistSummary.as_view(), name="summary"),
    path(
        "<int:sharelist_id>/credits/create",
        CreditCreate.as_view(),
        name="credits-create",
    ),
    path(
        "<int:sharelist_id>/credits/<int:credit_id>",
        CreditView.as_view(),
        name="credits-view",
    ),
    path(
        "<int:sharelist_id>/credits/<int:credit_id>/update",
        CreditUpdate.as_view(),
        name="credits-update",
    ),
    path(
        "<int:sharelist_id>/credits/<int:credit_id>/delete",
        CreditDelete.as_view(),
        name="credits-delete",
    ),
]

expenshare/users/urls.py
from django.urls import path

from expenshare.users.views import (
    user_autocomplete_view,
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("autocomplete/search", view=user_autocomplete_view, name="autocomplete"),
]

expenshare/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """Default user for Expenshare."""

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

expenshare/sharelists/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from dal import autocomplete
from django import forms
from django.utils import timezone

from expenshare.users.models import User

from .models import Sharelist


class SharelistForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_method = "post"
        self.helper.add_input(Submit("submit", "Create"))

    users = forms.ModelMultipleChoiceField(
        queryset=User.objects,
        widget=autocomplete.ModelSelect2Multiple(
            url="users:autocomplete", attrs={"data-placeholder": "Autocomplete ..."}
        ),
    )

    class Meta:
        model = Sharelist
        fields = "__all__"


class CreditForm(forms.Form):
    name = forms.CharField(label="Name", max_length=30)
    datetime = forms.DateTimeField(label="Datetime", initial=timezone.now())
    amount = forms.DecimalField(max_digits=19, decimal_places=4)

    def __init__(self, sharelist_id, button_name, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.debtors = Sharelist.objects.get(id=sharelist_id).users.all()
        choices = [(d.id, d.username) for d in self.debtors]

        self.fields["debtors"] = forms.MultipleChoiceField(
            choices=choices,
            widget=forms.CheckboxSelectMultiple,
            initial=[c[0] for c in choices],
        )

        self.helper = FormHelper(self)
        self.helper.form_method = "post"
        self.helper.add_input(Submit("submit", button_name))

    def is_valid(self):
        res = super().is_valid()
        self.cleaned_data["debtors"] = [int(d) for d in self.cleaned_data["debtors"]]
        return res

expenshare/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

expenshare/index/views.py
from django.shortcuts import render

from expenshare.sharelists.services import user_sharelists_summary


def index(request):
    if not request.user.is_authenticated:
        return render(request, "index/welcome.html")

    context = {"sharelists": user_sharelists_summary(request.user)}
    return render(request, "index/index.html", context=context)

expenshare/sharelists/views.py
# from social_django.utils import load_strategy
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.http import HttpResponseForbidden, JsonResponse
from django.urls import reverse
from django.views.generic import TemplateView, View
from django.views.generic.edit import CreateView, FormView

from .forms import CreditForm, SharelistForm
from .models import Credit, Sharelist
from .services import (
    CreditCreateService,
    CreditDeleteService,
    CreditInfoService,
    CreditUpdateService,
)

User = get_user_model()


class SharelistCreate(LoginRequiredMixin, CreateView):
    model = Sharelist
    template_name = "sharelists/sharelist_create.html"
    success_url = "/"
    form_class = SharelistForm

    def form_valid(self, form, *args, **kwargs):
        # creator is not selected on the client side, thus shoud bw added by default on server side
        form.cleaned_data["users"] |= User.objects.filter(pk=self.request.user.pk)
        return super().form_valid(form, *args, **kwargs)


class SharelistMain(LoginRequiredMixin, TemplateView):
    template_name = "sharelists/sharelist_view_main.html"
    nbar = "main"
    pagination_limit = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active_sharelist"] = Sharelist.objects.get(id=context["sharelist_id"])

        paginator = Paginator(
            Credit.objects.get_sharelist_credits_with_user_debt(
                self.request.user.pk, context["sharelist_id"]
            ),
            self.pagination_limit,
        )

        page_number = self.request.GET.get("page", 1)
        page_obj = paginator.get_page(page_number)
        context["paginator"] = paginator
        context["page_obj"] = page_obj
        context["nbar"] = self.nbar
        return context


class SharelistSummary(LoginRequiredMixin, TemplateView):
    template_name = "sharelists/sharelist_view_summary.html"
    nbar = "summary"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active_sharelist"] = Sharelist.objects.get(id=context["sharelist_id"])

        member_to_user_debt = Sharelist.objects.get_user_debts_per_member(
            context["sharelist_id"], self.request.user.id
        )
        member_to_user_credit = Sharelist.objects.get_user_credits_per_member(
            context["sharelist_id"], self.request.user.id
        )

        per_member_summary = [
            {
                "id": u.id,
                "username": u.username,
                "user_debt": member_to_user_debt.get(u.id, Decimal(0.0)),
                "user_credit": member_to_user_credit.get(u.id, Decimal(0.0)),
            }
            for u in context["active_sharelist"].users.all()
            if u.id != self.request.user.id
        ]

        for entity in per_member_summary:
            entity["user_balance"] = entity["user_credit"] - entity["user_debt"]

        context["per_member_summary"] = per_member_summary
        context["nbar"] = self.nbar
        return context


class CreditFormView(LoginRequiredMixin, FormView):
    form_class = CreditForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({"sharelist_id": self.kwargs["sharelist_id"]})
        return kwargs


class CreditCreate(CreditFormView):
    template_name = "sharelists/credit_create.html"

    def get_success_url(self):
        return reverse(
            "sharelists:view", kwargs={"sharelist_id": self.kwargs["sharelist_id"]}
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["button_name"] = "Create"
        return kwargs

    def form_valid(self, form):
        service = CreditCreateService(
            self.kwargs["sharelist_id"],
            form.cleaned_data["debtors"],
            self.request.user.pk,
            form.cleaned_data["name"],
            form.cleaned_data["datetime"],
            form.cleaned_data["amount"],
        )
        service.execute()
        return super().form_valid(form)


class CreditUpdate(CreditFormView):
    template_name = "sharelists/credit_create.html"

    def get_success_url(self):
        return reverse(
            "sharelists:credits-view",
            kwargs={
                "sharelist_id": self.kwargs["sharelist_id"],
                "credit_id": self.kwargs["credit_id"],
            },
        )

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()

        credit_obj = (
            Credit.objects.filter(id=self.kwargs["credit_id"])
            .prefetch_related("debts")
            .get()
        )
        data = {
            "name": credit_obj.name,
            "datetime": credit_obj.datetime,
            "amount": credit_obj.amount,
            "debtors": [d.debtor_id for d in credit_obj.debts.all()],
        }

        kwargs["initial"] = data
        kwargs["button_name"] = "Update"
        return kwargs

    def form_valid(self, form):
        service = CreditUpdateService(
            self.kwargs["credit_id"],
            self.kwargs["sharelist_id"],
            form.cleaned_data["debtors"],
            self.request.user.pk,
            form.cleaned_data["name"],
            form.cleaned_data["datetime"],
            form.cleaned_data["amount"],
        )
        service.execute()
        return super().form_valid(form)


class CreditView(LoginRequiredMixin, TemplateView):
    template_name = "sharelists/credit_view.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        service = CreditInfoService(
            context["sharelist_id"], context["credit_id"], self.request.user.pk
        )
        credit_info = service.execute()
        context["credit_info"] = credit_info
        return context


class CreditDelete(LoginRequiredMixin, View):
    pattern_name = "sharelists:view"

    def delete(self, request, *args, **kwargs):
        credit_id = kwargs.pop("credit_id", None)

        service = CreditDeleteService(
            credit_id,
            self.request.user.pk,
        )

        try:
            service.execute()
        except PermissionDenied as e:
            return HttpResponseForbidden(content=str(e))

        url = reverse(self.pattern_name, kwargs=kwargs)
        return JsonResponse(data={"success_url": url}, status=200)

expenshare/users/views.py
from dal import autocomplete
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        return self.request.user.get_absolute_url()  # type: ignore [union-attr]

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class UserAutocompleteView(LoginRequiredMixin, autocomplete.Select2QuerySetView):

    model_field_name = "username"
    model = User
    limit_by = 5

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.exclude(pk=self.request.user.pk).order_by(self.model_field_name)[
            : self.limit_by
        ]
        return qs


user_autocomplete_view = UserAutocompleteView.as_view()

expenshare/templates/sharelists/credit_create.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="col-12 pt-2 justify-content-center">
    {% crispy form %}
  </div>
</div>
{% endblock %}

expenshare/templates/sharelists/credit_view.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="row align-items-center my-1">
  <div class="col-6 col-md-8 col-xl-8">
    <h1>
      {{ credit_info.name }}
    </h1>
  </div>
  <div class="col-3 col-md-2 col-xl-2 pr-1">
    <a class="btn btn-primary btn-block" href="{% url 'sharelists:credits-update' sharelist_id credit_id %}">Edit</a>
  </div>
  <div class="col-3 col-md-2 col-xl-2 pl-1">
    <a class="btn btn-danger btn-block" data-toggle="modal" data-target="#deleteConfirm">Delete</a>
    <div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-labelledby="DeleteConfirmCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="DeleteConfirmCenterTitle">Are you sure you want to delete this?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>{{ credit_info.name }}</p>
                <p>Price: {{ credit_info.amount }}</p>
                <div id="alerts">
                </div>
            </div>
            <div class="modal-footer">
                <button id="delete-credit-button" type="button" class="btn btn-outline-danger">Yes</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
            </div>
            </div>
        </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <p>
      Price: {{ credit_info.amount }}
    </p>
    <p>
      Datetime: {{ credit_info.datetime }}
    </p>
  </div>
</div>
<div class="row">
  <div class="col-12">
    Debts:
  </div>
</div>
{% for debt in credit_info.debts %}
<div class="row no-gutters align-items-center py-2 border-bottom-2">
  <div class="col-3 pl-2">
    {{ debt.username }}
  </div>
  <div class="col-7 text-right pr-2">
    {{ debt.amount }}
  </div>
</div>
{% endfor %}
{% endblock %}

{% block extra_js %}

{% endblock %}

expenshare/templates/sharelists/sharelist_create.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="col-12 justify-content-center">
    {% crispy form %}
  </div>
</div>
{% endblock %}

expenshare/templates/sharelists/sharelist_view_base.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="row align-items-center my-1">
  <div class="col-7 col-md-9 col-xl-10">
    <h2>{{ active_sharelist.name }}</h2>
  </div>
  <div class="col-5 col-md-3 col-xl-2">
      <a class="btn btn-primary btn-block" href="{% url 'sharelists:credits-create' sharelist_id %}">New credit</a>
  </div>
</div>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link {% if nbar == 'main' %}active{% endif %}" href="{% url 'sharelists:view' sharelist_id %}">Credits</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% if nbar == 'summary' %}active{% endif %}" href="{% url 'sharelists:summary' sharelist_id %}">Summary</a>
  </li>
</ul>
{% block sharelists_content %}{% endblock %}
{% endblock %}

expenshare/templates/sharelists/sharelist_view_main.html
{% extends 'sharelists/sharelist_view_base.html' %}

{% block sharelists_content %}
{% for credit in page_obj.object_list %}
<div class="row no-gutters align-items-center py-2 border-bottom-2">
  <div class="col-7 pl-2">
    <a href="{% url 'sharelists:credits-view' sharelist_id credit.id %}">
      <h5 class="mb-0">{{ credit.name }}</h5>
    </a>
    <p class="mb-0">{{ credit.amount }}</p>
    </div>
  <div class="col-3">
    <h4 class="text-right font-weight-bold mb-0">
        {% if credit.debts.exists %}
            {{ credit.debts.get.amount }}
        {% else %}
            0.0
        {% endif %}
    </h4>
  </div>
</div>
{% endfor %}
<div class="row pt-2 justify-content-center">
  <div class="col-12">
      <nav aria-label="Debts page navigation">
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          {% if page_obj.has_next %}
          <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
          </a>
          </li>
          {% endif %}
        </ul>
      </nav>
  </div>
</div>
{% endblock %}

expenshare/templates/sharelists/sharelist_view_summary.html
{% extends 'sharelists/sharelist_view_base.html' %}

{% block sharelists_content %}
{% for c in per_member_summary %}
<div class="row no-gutters align-items-center py-2 border-bottom-2">
    <!-- <div class="col-2">
      <img class="img-fluid rounded-circle d-block mx-auto avatar-img" src="{{ c.photo }}">
    </div> -->
    <div class="col-7 pl-2">
      <h5 class="mb-0">{{ c.username }}</h5>
      <p class="mb-0">Owns you: {{ c.user_credit|floatformat:2 }}
      <p class="mb-0">You own: {{ c.user_debt|floatformat:2 }}
    </div>
    <div class="col-3">
      <h4 class="text-right font-weight-bold mb-0">
          {{ c.user_balance|floatformat:2 }}
      </h4>
    </div>
  </div>
{% endfor %}
{% endblock %}